### ISSUE TITLE
camera view image issues

### ISSUE THREAD

**Issue by lalamax3d** [jdnichollsc/IonPhaser#3]
in marketing screens on ionic market place, impression i get was, camera app taking snap shot
after that
1- filters can be applied
2- rectangle drawn on top of image (cropping) 

i am working on an app, where i wanted to do this, camera image image app with canvas on top drawing (images) i was previously using / testing fabric js. noticed somebody created a demo with phaser sounds interestering.
practically for me, at this point, camera image filters simply didn't worked (android) nothing happens on clicking them. primarily no cropping option appeard after taking image. as shown in video on ionic

**Comment by jdnichollsc** [comment]
Hi @lalamax3d 

Thanks for report this issue, let me test in other Android devices.

Regards, Nicholls

**Comment by jdnichollsc** [comment]
@lalamax3d Can you share me a video from your mobile device? Maybe using https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free&hl=es_419

If you want my email is jdnichollsc@hotmail.com

**Comment by jdnichollsc** [comment]
@lalamax3d about the cropping option, this feature from the plugin **cordova-plugin-camera**, with the property **allowEdit** in **true**
