### ISSUE TITLE
Status Bar Bug

### ISSUE THREAD

**Issue by matheusgs05** [jdnichollsc/IonPhaser#4]
When i try to change the Status Bar configuration, the changes only apply when the app goes to background and foreground or when I pull the notification bar on iOS.
Can you take a look at that please?
On a new Ionic project, the Status Bar works perfect.

**Comment by jdnichollsc** [comment]
Hi man, thanks for report this issue, let me check to fix that.
Regards, Nicholls

**Comment by jdnichollsc** [comment]
Can you remove and add again the cordova plugin with the following commands? :)
```
cordova plugin rm cordova-plugin-statusbar --save
cordova plugin add cordova-plugin-statusbar --save
```
