### ISSUE TITLE
Ionic 2 support

### ISSUE THREAD

**Issue by jdnichollsc** [jdnichollsc/IonPhaser#5]

**Comment by hmanprod** [comment]
Any news here ? About ionic 3 maybe ?

**Comment by jdnichollsc** [comment]
Let me try with the new version of Phaser and migrate the code, because with the old version exist issues with TypeScript

**Comment by jdnichollsc** [comment]
We can use the new WebComponent https://github.com/proyecto26/ion-phaser

**Comment by jdnichollsc** [comment]
And for Phaser 2 => https://github.com/proyecto26/ion-phaser-ce
